### ISSUE TITLE
NorthQ app crashed

### ISSUE THREAD

**Issue by lcansby** [abeggled/com.northq#1]
After added NOQ_NQ-9021 I get this error when loading app.

module.js:491
throw err;
^
Error: Cannot find module 'homey-meshdriver'
at Function.Module._resolveFilename (module.js:489:15)
at Function.Module._load (module.js:439:25)
at Module.require (module.js:517:17)
at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
at require (internal/module.js:11:18)
at Object.<anonymous> (/drivers/NQ9021/device.js:4:21)
at Module._compile (module.js:573:30)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at tryModuleLoad (module.js:470:12)

Exit code: 1
Exit signal: null

**Comment by abeggled** [comment]
Thanks for your report.

"_After added NOQ_NQ-9021 I get this error when loading app._"
Means this you have paired the NQ-9021 and installed the app later?

- Which Homey Version are you running on?
- Which Version of NorthQ Power Reader do you want to pair? (green or blue one)?

Can you do the following:
1. remove(unpair) the NQ-9021 from homey
2. reset the NQ-9021 by pressing the inclusion button 7 times (wait for acknowledge by additional blinks)
3. pair the NQ-9021 by adding the device from the App
4. see if the error occour also

Thank you for your cooperation.

**Comment by lcansby** [comment]
Homey version 1.5.3
Green NorthQ Power Reader

Followed your steps but I get the same error

`module.js:491
throw err;
^

Error: Cannot find module 'homey-meshdriver'
at Function.Module._resolveFilename (module.js:489:15)
at Function.Module._load (module.js:439:25)
at Module.require (module.js:517:17)
at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
at require (internal/module.js:11:18)
at Object.<anonymous> (/drivers/NQ9021/device.js:4:21)
at Module._compile (module.js:573:30)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at tryModuleLoad (module.js:470:12)


Exit code: 1
Exit signal: null`

**Comment by abeggled** [comment]
Fixed the "Cannot find module 'homey-meshdriver' - issue" with Version 0.0.5
